#include <kprintf.c>
#include <stddef.h>
#include <stdint.h>
#include "dependencies/string.c"
#include "dependencies/io.c"
#include "dependencies/system.c"
#include "drivers.c"
#include "execute/gdt.c"
#include "execute/idt.c"
#include "execute/loader.c"